### ISSUE TITLE
how to get snapshot image from video

### ISSUE THREAD

**Issue by lenhatvu** [SuRGeoNix/MediaRouter#7]
Hi,

can you help me get snapshot (as Bitmap or save to jpeg file) from video ?

**Comment by SuRGeoNix** [comment]
I cannot do that for you dude. Just convert the Texture(in case of HW Decoding) or aFrame (in case of SW Decoding) data to bitmap.

**Comment by lenhatvu** [comment]
Hi,

I am trying to convert Texture to Bitmap b using this method but alway get the error at:
 var mapSource = _device.ImmediateContext.MapSubresource(texture, 0, MapMode.Read, MapFlags.None);

SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

Please help me complete this function.

///////////////////////////////////////////////////////////////////////////
private Bitmap ConvertTexture2DToBitmap(Texture2D texture)
        {
            Bitmap bitmap = null;

            if (texture != null)
            {
                int width = texture.Description.Width;
                int height = texture.Description.Height;

                // Get the desktop capture texture
                var mapSource = _device.ImmediateContext.MapSubresource(texture, 0, MapMode.Read, MapFlags.None);

                // Create Drawing.Bitmap
                bitmap = new System.Drawing.Bitmap(width, height, PixelFormat.Format32bppArgb);
                var boundsRect = new System.Drawing.Rectangle(0, 0, width, height);

                // Copy pixels from screen capture Texture to GDI bitmap
                var mapDest = bitmap.LockBits(boundsRect, ImageLockMode.WriteOnly, bitmap.PixelFormat);
                var sourcePtr = mapSource.DataPointer;
                var destPtr = mapDest.Scan0;
                for (int y = 0; y < height; y++)
                {
                    // Copy a single line 
                    Utilities.CopyMemory(destPtr, sourcePtr, width * 4);

                    // Advance pointers
                    sourcePtr = IntPtr.Add(sourcePtr, mapSource.RowPitch);
                    destPtr = IntPtr.Add(destPtr, mapDest.Stride);
                }

                // Release source and dest locks
                bitmap.UnlockBits(mapDest);
                _device.ImmediateContext.UnmapSubresource(texture, 0);

                //// Save the output
                //bitmap.Save("C:\\" + DateTime.Now.Ticks + ".jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
            }

            return bitmap;
        }

**Comment by pubpy2015** [comment]
Hi,

This is funtion to convert TextureRGB to bitmap:

public static System.Drawing.Bitmap ConvertTexture2DToBitmap(SharpDX.Direct3D11.Texture2D texture)
        {
            try
            {
                //System.Diagnostics.Stopwatch st = new System.Diagnostics.Stopwatch();
                //st.Start();

                var device = texture.Device;
                var originDesc = texture.Description;

                var desc = new Texture2DDescription
                {
                    CpuAccessFlags = CpuAccessFlags.Read,
                    BindFlags = BindFlags.None,
                    Usage = ResourceUsage.Staging,
                    Width = originDesc.Width,
                    Height = originDesc.Height,
                    Format = originDesc.Format,
                    MipLevels = 1,
                    ArraySize = 1,
                    SampleDescription =
        {
            Count = 1,
            Quality = 0
        },
                    OptionFlags = ResourceOptionFlags.Shared
                };

                var texture2D = new Texture2D(device, desc);

                device.ImmediateContext.CopyResource(texture, texture2D);

                var mapSource = device.ImmediateContext.MapSubresource(texture2D, 0, MapMode.Read, MapFlags.None);

                var bitmap = new System.Drawing.Bitmap(desc.Width, desc.Height);
                var boundsRect = new System.Drawing.Rectangle(0, 0, desc.Width, desc.Height);

                var mapDest = bitmap.LockBits(boundsRect, ImageLockMode.WriteOnly, bitmap.PixelFormat);
                var sourcePtr = mapSource.DataPointer;
                var destPtr = mapDest.Scan0;

                for (var y = 0; y < desc.Height; y++)
                {
                    Utilities.CopyMemory(destPtr, sourcePtr, desc.Width * 4);

                    sourcePtr = IntPtr.Add(sourcePtr, mapSource.RowPitch);
                    destPtr = IntPtr.Add(destPtr, mapDest.Stride);
                }

                bitmap.UnlockBits(mapDest);
                device.ImmediateContext.UnmapSubresource(texture2D, 0);

                Utilities.Dispose(ref texture2D);

                bitmap = ConvertToBGRA(bitmap);

                //st.Stop();
                //System.Windows.Forms.MessageBox.Show(st.ElapsedMilliseconds.ToString());

                return bitmap;
            }
            catch
            {
                
            }
            return null;
        }

        public static System.Drawing.Bitmap ConvertToBGRA(System.Drawing.Bitmap originalImage)
        {
            try
            {
                BitmapData sourceData = originalImage.LockBits
                                (new System.Drawing.Rectangle(0, 0, originalImage.Width, originalImage.Height),
                                ImageLockMode.ReadOnly, System.Drawing.Imaging.PixelFormat.Format32bppArgb);

                byte[] resultBuffer = new byte[sourceData.Stride * sourceData.Height];
                Marshal.Copy(sourceData.Scan0, resultBuffer, 0, resultBuffer.Length);
                originalImage.UnlockBits(sourceData);

                byte sourceBlue = 0, resultBlue = 0,
                        sourceGreen = 0, resultGreen = 0,
                        sourceRed = 0, resultRed = 0;


                for (int k = 0; k < resultBuffer.Length; k += 4)
                {
                    sourceBlue = resultBuffer[k];
                    sourceGreen = resultBuffer[k + 1];
                    sourceRed = resultBuffer[k + 2];

                    resultBlue = sourceRed;
                    resultRed = sourceBlue;
                    resultGreen = sourceGreen;

                    resultBuffer[k] = resultBlue;
                    resultBuffer[k + 1] = resultGreen;
                    resultBuffer[k + 2] = resultRed;
                }

                System.Drawing.Bitmap resultBitmap = new System.Drawing.Bitmap(originalImage.Width, originalImage.Height,
                                                    System.Drawing.Imaging.PixelFormat.Format32bppArgb);

                BitmapData resultData = resultBitmap.LockBits
                                        (new System.Drawing.Rectangle(0, 0, resultBitmap.Width, resultBitmap.Height),
                                        ImageLockMode.WriteOnly, System.Drawing.Imaging.PixelFormat.Format32bppArgb);

                Marshal.Copy(resultBuffer, 0, resultData.Scan0, resultBuffer.Length);
                resultBitmap.UnlockBits(resultData);

                originalImage.Dispose();
                originalImage = null;

                return resultBitmap;
            }
            catch
            {
                
            }
            return null;
        }

**Comment by pubpy2015** [comment]
this is funtion convert Hardware Texture2D to bitmap

public static System.Drawing.Bitmap ConvertHardwareTexture2DToBitmap(SharpDX.Direct3D11.Texture2D texture)
        {
            try
            {
                //System.Diagnostics.Stopwatch st = new System.Diagnostics.Stopwatch();
                //st.Start();

                var device = texture.Device;
                var originDesc = texture.Description;

                var desc = new Texture2DDescription
                {
                    CpuAccessFlags = CpuAccessFlags.Read,
                    BindFlags = BindFlags.None,
                    Usage = ResourceUsage.Staging,
                    Width = originDesc.Width,
                    Height = originDesc.Height,
                    Format = originDesc.Format,
                    MipLevels = 1,
                    ArraySize = 1,
                    SampleDescription =
        {
            Count = 1,
            Quality = 0
        },
                    OptionFlags = ResourceOptionFlags.Shared
                };

                var texture2D = new Texture2D(device, desc);

                device.ImmediateContext.CopyResource(texture, texture2D);

                var mapSource = device.ImmediateContext.MapSubresource(texture2D, 0, MapMode.Read, MapFlags.None);

                var bitmap = new System.Drawing.Bitmap(desc.Width, desc.Height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);
                var boundsRect = new System.Drawing.Rectangle(0, 0, desc.Width, desc.Height);

                var mapDest = bitmap.LockBits(boundsRect, ImageLockMode.WriteOnly, bitmap.PixelFormat);
                var sourcePtr = mapSource.DataPointer;
                var destPtr = mapDest.Scan0;

                TransformImage_NV12_TO_RGB24(destPtr, sourcePtr, desc.Width, desc.Height);

                bitmap.UnlockBits(mapDest);
                device.ImmediateContext.UnmapSubresource(texture2D, 0);

                Utilities.Dispose(ref texture2D);

                //st.Stop();
                //System.Windows.Forms.MessageBox.Show(st.ElapsedMilliseconds.ToString());

                bitmap.RotateFlip(System.Drawing.RotateFlipType.RotateNoneFlipXY);
                return bitmap;
            }
            catch
            {
                
            }
            return null;
        }

        unsafe private static void TransformImage_NV12_TO_RGB24(IntPtr pDest, IntPtr pSrc, int dwWidthInPixels, int dwHeightInPixels)
        {
            try
            {
                uint imageWidth = (uint)dwWidthInPixels;
                uint widthHalf = imageWidth / 2;
                uint imageHeight = (uint)dwHeightInPixels;

                byte* nv12Data = (byte*)pSrc;
                byte* rgbData = (byte*)pDest;

                uint dataSize = imageWidth * imageHeight * 3;

                for (uint y = 0; y < imageHeight; y++)
                {
                    for (uint x = 0; x < imageWidth; x++)
                    {
                        uint xEven = x & 0xFFFFFFFE;
                        uint yEven = y & 0xFFFFFFFE;
                        uint yIndex = y * imageWidth + x;
                        uint cIndex = imageWidth * imageHeight + yEven * widthHalf + xEven;

                        byte yy = nv12Data[yIndex];
                        byte cr = nv12Data[cIndex + 0];
                        byte cb = nv12Data[cIndex + 1];

                        uint outputIndex = (dataSize - (y * imageWidth + x) * 3) - 3;

                        rgbData[outputIndex + 0] = (byte)Math.Min(Math.Max((yy + 1.402 * (cr - 128)), 0), 255);
                        rgbData[outputIndex + 1] = (byte)Math.Min(Math.Max((yy - 0.344 * (cb - 128) - 0.714 * (cr - 128)), 0), 255);
                        rgbData[outputIndex + 2] = (byte)Math.Min(Math.Max((yy + 1.772 * (cb - 128)), 0), 255);
                    }
                }
            }
            catch
            {
                
            }
        }

**Comment by pubpy2015** [comment]
I dont know how to convert YUV texture to bitmap

**Comment by SuRGeoNix** [comment]
Why don't you use my code on MediaRenderer.cs to convert it on GPU to an RGBA texture2d and then just read that texture2d? (instead of present it just save it - I might also have some code in utils for that)

**Comment by pubpy2015** [comment]
In Utils.cs you only have code for convert Bitmap to Textuxe2D, that right ?
I need convert Textuxe2D (in MediaFrame) to Bitmap.
above code convert TextureRGB and TextureHW to Bitmap.
other media frame with textureY, textureU, textureV i dont know how to convert

// Video Textures
        public Texture2D textureHW;
        public Texture2D textureRGB;
        public Texture2D textureY;
        public Texture2D textureU;
        public Texture2D textureV;

**Comment by SuRGeoNix** [comment]
Yep, utils will not help you... just check them. If you dont care about speed you could process YUV as REST format so it will process it with sws_scale and you will get an RGBA texture2d. Will this work for you?
